import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Header } from "@/components/navigation/header/Header";
import { ibmPlexSansJp } from "./fonts";

export const metadata: Metadata = {
  title: "My Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={`${ibmPlexSansJp.className} font-body`}>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
