import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Container } from "@/components/layout/container/Container";
import { Header } from "@/components/navigation/header/Header";

export const metadata: Metadata = {
  title: "My Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Container>
            <Header />
          </Container>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
